-- CRIAR NOVO BD
CREATE DATABASE GREENHOUSE;

-- UTILIZANDO BANCO DE DADOS

USE GREENHOUSE;

-- CRIANDO UMA TABELA

CREATE TABLE `GREENHOUSE` . `PLANTS`(
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL
		DEFAULT CURRENT_TIMESTAMP ON
        UPDATE CURRENT_TIMESTAMP,
	`SENSOR_LEVEL` CHAR(5) DEFAULT NULL,
    PRIMARY KEY `PK_PLANT_NAME` (`PLANT_NAME`)
);

-- COMANDOS DE INSE~ÇÃO DE DADOS
INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Orquidea', 10, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Coqueiro', 15, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Maria Joana', 20, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Violeta', 90, 'MED');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Haze-prop', 30, 'MED');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Samambaia', 40, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Capulho', 50, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Dente-leão', 25, 'MED');

-- EXECUNTANDO COMANDOS
-- CONSULTANDO TUDO DA TABELA
SELECT * FROM `GREENHOUSE`.`PLANTS`; 

-- ESPECIFICANDO APENAS AS COLUNAS DESEJADAS
SELECT `PLANT_NAME`, `SENSOR_EVENT`
FROM `PLANTS`;

-- APLICANDO FILTROS NO REGISTRO DE DADOS
SELECT * FROM PLANTS
WHERE SENSOR_LEVEL = 'HIGH'
AND SENSOR_VALUE >= 10 AND SENSOR_VALUE <= 20;

-- CALUSULA DE ORDENAÇÃO
SELECT *
FROM `PLANTS`
WHERE SENSOR_VALUE < 50
ORDER BY SENSOR_VALUE DESC;

-- FUNÇÕES DE AGRUPAMENTO
-- top
SELECT `PLANT_NAME`, `SENSOR_VALUE`
FROM `PLANTS`
WHERE SENSOR_VALUE >= 20;

-- COUNT
SELECT COUNT(*) `PLANT_NAME`, `SENSOR_LEVEL`
FROM `PLANTS`
GROUP BY SENSOR_LEVEL;

-- MIN AND MAX
SELECT MIN(SENSOR_VALUE)
FROM `PLANTS`;

-- SUM
SELECT SUM(SENSOR_VALUE)
FROM `PLANTS`;

-- AVG
SELECT AVG(SENSOR_VALUE)
FROM `PLANTS`;

-- LIKE
SELECT * FROM PLANTS
WHERE PLANT_NAME LIKE 'M';

-- COMANDO UPDATE PARA ATUALIZAR REGISTROS DE DADOS
SELECT * FROM PLANTS;
UPDATE PLANTS 
SET SENSOR_VALUE = 90, SENSOR_LEVEL = 'HIGH'
WHERE PLANT_NAME = 'Violeta';

-- APAGANDO REGISTROS DA TABELA DO BANCO DE DADOS
DELETE FROM PLANTS 
WHERE PLANT_NAME = 'Coqueiro';



