SELECT 
	NF.NRO_NOTA AS NUMERO,
    NF.NM_CLIENTE AS NOME,
    PRD.DESC_PRODUTO AS PRODUTO,
    INF.QTD_PRODUTO AS QUNATIDADE
FROM
	NOTA_FISCAL AS NF,
    ITEM_NOTA_FISCAL AS INF,
    PRODUTO AS PRD
WHERE 
	ND.NRO_NOTA = INF.NRO_NOTA
    AND INF.COD_PRODUTO = PRD.COD_PRODUTO
    AND PRD.COD_PRODUTO = 3