SELECT 
	NF.NM_CLIENTE AS CLIENTE,
    SUM(INF.VL_TOTAL) AS VALOR
FROM
	NOTA_FISCAL AS NF,
    ITEM_NOTA_FISCAL AS INF
WHERE
NF.NRO_NOTA = INF.NRD_NOTA
GROUP BY 
	NF.NM_CLIENTE
ORDER BY 
	VALOR DESC;
    